// prompts/analysis-teaser.js
//
// The LANDING-PAGE TEASER analysis. Mission: give real, surprising value up top,
// prove we read the CV closely, make the reader hungry for the rest — without the
// full rewrite plan (that unlocks on sign-up). Small output so the strong model
// runs cheap. Output is intentionally LEAN — only the fields TeaserDisplay renders
// (the two scan gates, the recruiter reaction, buried credentials, the questions)
// plus scenario_tags (internal steering, carried to the deep pass). Everything the
// deep analysis needs but the teaser doesn't show is generated by the deep pass,
// not here — so a free landing visitor never pays for the full record.
//
// Same never-fabricate law as the full analysis: only what the CV evidences.

import { scenarioList } from './scenarios.js';

const NEVER_FABRICATE = `Use ONLY what the CV (and job ad, if given) actually proves. Never invent employers, dates, titles, skills, numbers or achievements. Reference THIS candidate's real phrases, roles and companies — every line must be impossible to paste onto someone else's CV. Detect the CV's language and write ALL output in it.`;

export function buildAnalysisTeaserPrompt(cvText, jobText, hasJobText, layoutNote = '') {
  return [
    {
      role: 'system',
      content: `You are a top-tier HR strategist and sharp CV writer doing a fast, incisive first read of a candidate's CV${hasJobText ? ' against a specific job ad' : ''}. You produce a short, high-impact TEASER: enough genuine insight to make the candidate think "they really get me", while holding back the full rewrite plan. ${NEVER_FABRICATE}`,
    },
    {
      role: 'user',
      content: `Produce a TEASER analysis as VALID JSON only — no markdown, no comments, no trailing commas. Be specific and concrete; generic advice is failure.

TONE LAW — write like a sharp, plain-spoken human who actually read THIS CV. The reader should feel precisely seen, not flattered. HARD BAN on praise adjectives and hype: never use rare, elite, exceptional, world-class, stellar, prestigious, impressive, sought-after, tier-one, pedigree, mastery, pioneer, or any synonym. Never use exclamation or salesman warmth. Every positive must be a CONCRETE FACT lifted from the CV (a named role, a thing built, a number) — if you cannot point to the fact, delete the sentence. State problems plainly as fixable. Specificity is the value; enthusiasm is not.

SCENARIO (classify first; never printed to the user): choose 1-2 from the list and let them steer scan_verdict, scan_reason and hr_first_seconds — e.g. a senior portfolio/consultant whose standing practice spans shorter corporate stints is not a job-hopper, and a long-spanning consultancy means the candidate was not actually between jobs. Prove it through the specificity of the read, never the label.
SCENARIO LIST: ${scenarioList(hasJobText)}

FIELDS (full quality — shown in full, must stand on their own as real value):
- cv_data: { Name, Seniority, Industry, Country } from the CV (Country = the most-recent role's country, not the contact block).
- analysis.scenario_tags: ARRAY of the 1-2 chosen scenario tags (internal steering + carried forward to the deep analysis; never rendered to the user).

THE TWO-STAGE SCAN — a real CV runs two binary gates before a human ever reads it properly, and your scan reports both as a clean PASS or FAIL. Gate 1 is the machine (ATS); Gate 2 is the ~7-second human skim. A CV that fails Gate 1 is never seen; a CV that passes Gate 1 but fails Gate 2 is binned in seconds. Do NOT hedge the verdict — it is "pass" or "fail", nothing else. Then state the single decisive reason in plain language.
- analysis.ats_verdict: EXACTLY "pass" or "fail" — would this CV survive automated parsing/keyword screening as written? Fail it for real, concrete parser problems (a two-column layout that scrambles, a scanned/image CV, dates a parser can't read, missing the role's core terms entirely), not for taste. The CANDIDATE RECORD below is faithful, structured data — it tells you NOTHING about how the physical file parses, so do NOT infer parse problems from it. The ONLY window into the real file is the LAYOUT SIGNAL block: drive this verdict from it. A flagged multi-column or scanned/image layout is a concrete FAIL; quote the offending date string verbatim when its formats are inconsistent. If there is NO LAYOUT SIGNAL block, the file's geometry is unknown — pass the ATS gate unless the record itself is missing the role's core terms.
- analysis.ats_reason: 1-2 sentences naming the ONE decisive thing — if fail, the specific reason it gets dropped (quote the offending detail); if pass, the concrete reason it parses cleanly. No generic "optimise keywords". On a PASS this is the one brief sentence shown on the card; on a FAIL it is the blunt bottom-line reason it is dropped.
- analysis.ats_snags: ARRAY of UP TO 3 ordered { "point": "", "detail": "" } shown ONLY when ats_verdict is "fail" — each names ONE real, concrete parsing problem in THIS CV. "point" = the exact offending element, quoted from the CV (a real two-column block, a graphic/photo, an unusual section heading, an unreadable date format, a core role term that is simply absent); "detail" = the one-line consequence for the parser. NEVER invent a problem to reach three — return only as many as the CV genuinely has, down to one. [] whenever ats_verdict is "pass".
- analysis.scan_verdict: EXACTLY "pass" or "fail" — in the ~7-second skim of the TOP of this CV, does a recruiter keep reading or bin it? Pass means a clear, legible, relevant top-line; fail means the eye hits a reason to stop (illegible title, stale most-recent date, no obvious fit, wall of text).
- analysis.scan_reason: 1-2 sentences — if fail, the single top reason they stop (the specific thing their eye snags on); if pass, the specific thing that earns the next two minutes. Reference THIS CV's real top-line facts.
- analysis.scan_snags: ARRAY of UP TO 3 ordered { "point": "", "detail": "" } shown ONLY when scan_verdict is "fail" — they walk through what the recruiter's eye actually hits at the TOP of THIS CV. "point" = the raw fact quoted VERBATIM from the CV with NO framing words — write the real title / date-range / tenure itself (e.g. "Salsita Software | Nov 2022 – Oct 2023"), never "Eye lands on…"; "detail" = ONE short, plain statement of the observed fact only — what the recruiter literally sees on the page (e.g. "An 11-month tenure that ended over a year ago." / "A 10-month tenure directly preceding the Salsita stint."). Do NOT elaborate, interpret, or append a consequence/implication clause — BANNED: "leaving your focus ambiguous", "indicating consecutive short-term commitments", "which clouds…", and any "raising/suggesting…" tail. State the fact and STOP. Do NOT phrase any "detail" as a question — the open question belongs ONLY in hr_first_seconds. NEVER invent a snag to reach three; return only as many as the top-line genuinely warrants, down to one. [] whenever scan_verdict is "pass".
- analysis.buried_credentials: ARRAY of AT MOST 2-3 { "tag": "", "name": "" } — the candidate's most recognisable names (employer, client, or brand from the CV) that sit too LOW on the page to survive a 7-second scan. "tag" is a 3-6 char label for the relationship (e.g. "BANK", "CLIENT", "BRAND"); "name" is the real name (e.g. "eBay"). Only names that genuinely carry weight and are genuinely buried. Exclude any name outside the recent visible-career window (~last 10-15 years); surfacing an old employer only amplifies an age signal. [] if none qualify.
- analysis.hr_first_seconds: the recruiter's RAW inner flash in the first ~7 seconds skimming the TOP of this CV — a fast gut reaction, NOT a considered assessment. RULES: write in FIRST PERSON as the recruiter ("Okay, senior product... wait, why did the last two jobs only last a year each?"), speak ABOUT the candidate as "they/this person", keep it SHORT and clipped (max ~40 words, 1-2 punchy sentences, fragments allowed) — a real skim has no time for full composed prose. Base it ONLY on what the eye hits first: current/most-recent title, the latest dates (recency/gap), apparent seniority. Land on ONE snap verdict or doubt. BAN clinical phrasing ("the candidate presents as", "this makes the focus feel ambiguous") — that is analysis, not a reflex. REALISTIC: not flattering, not cruel, includes the unfair-but-real instinct. Use THIS CV's real top-line facts. Shows the candidate the impression they cannot see. Do NOT wrap it in quotation marks — it is rendered inside quote marks already.
- analysis.nuance_clarifications: 1 to 4 short questions (as many as the CV genuinely warrants — do NOT pad to hit a number) that surface a REAL ambiguity or tension you noticed in THIS CV that the candidate may not have weighed — proof you read closely. Each names the specific detail (a date overlap, a location mismatch, a title that undersells) and why it matters. NOT marketing, NOT generic — specific and observational. Omit any you cannot make specific to this CV.
NO REPETITION (hard rule — the teaser reads as ONE page, and a reader who sees the same point three times feels handled, not understood): the scan_snags, hr_first_seconds and nuance_clarifications must each cover DIFFERENT ground. A specific issue (a date overlap, a short tenure, an age signal) belongs in exactly ONE of them — the place it lands hardest — and must NOT be restated, reworded, or alluded to in the others. Before you finish, scan your own output and delete any second mention of the same underlying fact.

OUTPUT EXACTLY THIS SHAPE:
{
  "cv_data": { "Name": "", "Seniority": "", "Industry": "", "Country": "" },
  "analysis": {
    "scenario_tags": [],
    "ats_verdict": "",
    "ats_reason": "",
    "ats_snags": [],
    "scan_verdict": "",
    "scan_reason": "",
    "scan_snags": [],
    "buried_credentials": [],
    "hr_first_seconds": "",
    "nuance_clarifications": []
  }
}

CANDIDATE RECORD (faithful structured facts extracted from the CV — judge ALL data: dates, gaps, tenures, role overlaps, seniority, buried names from THIS; roles are kept separate and any overlaps are surfaced in its "conflicts", so two short roles sitting alongside a longer engagement are a real signal, not a merge):
${cvText}
${layoutNote ? `\n${layoutNote}\n` : ''}
${hasJobText ? `JOB DESCRIPTION:\n${jobText}` : 'No job ad provided — assess the CV on its own merits against the norms of its own country; do NOT invent a target role or market.'}
`.trim(),
    },
  ];
}
