import { createClient } from '@supabase/supabase-js';
const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
const { data: u } = await sb.from('users').select('user_id').eq('email','npx10111@gmail.com').single();
const { data } = await sb.from('gen_data').select('content, created_at').eq('user_id', u.user_id).eq('type','analysis').order('created_at',{ascending:false}).limit(1);
const c = typeof data?.[0]?.content === 'string' ? JSON.parse(data[0].content) : data?.[0]?.content;
console.log('TOP KEYS', Object.keys(c));
console.log('JOB_EXTRACTION', JSON.stringify(c.job_extraction, null, 1));
console.log('BLUEPRINT KEYS', Object.keys(c.generation_framework?.cv_blueprint||{}));
console.log('SECTION_ORDER', JSON.stringify(c.generation_framework?.cv_blueprint?.section_order));
console.log('COVER_EVIDENCE', JSON.stringify(c.generation_framework?.cover_evidence, null, 1));
console.log('ADLEN', (c.job_text||'').length);
console.log('AD', (c.job_text||'').slice(0,3000));
console.log('GF KEYS', Object.keys(c.generation_framework||{}));
console.log('JOB_SELECTION', JSON.stringify(c.generation_framework?.cv_blueprint?.job_selection, null, 1));
console.log('TOP3', JSON.stringify(c.generation_framework?.cv_blueprint?.top_three_achievements, null, 1));
console.log('ANALYSIS KEYS', Object.keys(c.analysis||{}));
console.log('KW PRESENT', JSON.stringify(c.analysis?.ats_keywords_present));
console.log('KW MISSING', JSON.stringify(c.analysis?.ats_keywords_missing));
console.log('SCEN', JSON.stringify(c.analysis?.scenario_tags), JSON.stringify(c.job_match?.career_scenario));
